apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z mongodb-service 27017; do echo waiting for mongodb; sleep 2; done;']
      containers:
        - name: catalog-service
          image: catalog-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: MONGO_URI
              value: "mongodb://admin:password@mongodb-service:27017/catalog_db?authSource=admin"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: ClusterIP
  selector:
    app: catalog-service
  ports:
    - port: 3001
      targetPort: 3001